language: node_js
node_js:
 - "lts/*"
addons:
  apt:
    packages:
    - libgconf-2-4
services: 
cache:
  npm: true
  directories:
  - "~/.cache"
  - "./node_modules"
  - "~/.cache"
override:
  - npm ci
  - npm run cy:verify  
install:
  - npm ci
  - chmod +x node_modules/.bin/*
script:
  - npm run build
  - npm run test:unit
  - npm run serve & wait-on $TEST_URL_ENV
  # - npx run test:e2e --headless --mode production --url $TEST_URL_ENV --record --key $CYPRESS_RECORD_KEY_ENV
deploy:
  provider: heroku
  api_key:
    secure: rxWRzEpKMGvzkYo36Dp/PrUxkQQHKAKjEMTcEZg/fTrIDef7FWvN9W9DmwaMYhrXT6toGZ0NuLTcRDcMRXqZjIKvKA3ScFuhZTkRF9sj6CWzZXWniNPnDWY4xrGEoAWy4KHH3ua6DPjSYRL3UspFEUH0TopL1P9uqNNdS3TmfsgYhOcwf9DXF+Bhwvqid0PjNn/cCJoFtUrUkHVY7aIV1iuWqrjfAqz9HG2pv1f1xWfBZ9i3vb30vtbxPhlsws73Ekc2iOaqsadFUpfareGllICz6EHeHmQCnfdIACTTpVgqKiCQGHdqcqPej6J8r2xIrJUg8yawv8mZJw++YPlFy15KtLs/LfhdH+ons7dORBM1UYY1ItHPAsrwibdd4rRn4fJE8uc2Pj0l/cbUSnknZYEHlLKxgGwNREM8iLxMLX0UeSsZNGim6IGGoeu+9b5nn8/DSlcYOCsv6u7CxuJDp9X7tBXSFiOupmGWqWHgQIg/UjfblEt8jwtUUifEWSozFmYcA39+amCV84DtHoHJDmq1jQKbU9DsIqI5O1/EEbfanZC3Zy8gpCgYsPm++9vgjB6T5sIZokXJcjjjKI3dUpUyoYiGXl/ci68F6OSbZsMzLXkkw6W4XMl9zit+EQiqGBAmoCeG2Fp3BMLSFxGQ7NStACm4YNGO3v5+G+Q/p9U=
  app: mattrememberedproject
  on:
    repo: BantuLabTech/mattrememberedproject
    branch: master
  after_failure:
    - find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
env:
  global:
    - TEST_URL_ENV=http://localhost:8080
    - secure: zYiRJ5ho2YEzmfa+4XhSLgijUVS3lsh7IAsarilARrmxuPf0MlpFq9THDP143B0AvO3RDF77nKybBgZ4ojdih9gVrNdzv+eQSTjiwafnQDb8tfXujRKYmlSfiY5v+DUyBFGNyW7RJUXUX5Wx2M49LlAANg8jc4nIrt+mUaQYyMA2aI+lBKOp/n6ww+b84SoP7Ycq7GcD/o8vk9iva0I9ZPEYhKZgY3dlBbCCLIbz7YYFpaAIsW7dR/VP89Mqfa+63g1jo8U6XTmDM0a8mQ0MPjR2MpnTC1I/J9CtxXl2jVBJWPEM9JFIvlrG59vW/vqcT0uVnJiB8IeKo2JrK26Zq7THGQsrfMlkUVMOZ+6Qj6hfRBh38VbwSSdRLEWQNsYf+uJKJ8G2oVyGKtvAacJIbZJRpdTKIjhH1k/5JeO81gspyMtfMR8cQIl6PHp7AeV2QVY8dGSGWvbiJpPVVlRLlzK70KFVJskZlRTsxids1kMNIQJP32jYGkoYwVuVHIZK+1I2k1pfrTsImYV6/ojCTu7Ur7O1R4s8XoFXHbdZ6C8qgyn8ZmL6TVh/FTa6XS30dfMvoLu7xQvwPYVMfMqhVf2vyYk53NUdrJ9Gx5UxOZv3fLxqX4L72PUoTJX562pSesbzUdr0hw9aBEJVLG8RgQ1UU5gfd9yx1vKRiFhc4P8=
