language: node_js
node_js:
- lts/*
addons:
  apt:
    packages:
    - libgconf-2-4
services: 
cache:
  npm: true
  directories:
  - "~/.cache"
  - "./node_modules"
  - "~/client/.cache"
  - "./client/node_modules"

# override:
# install packages in client for testing and building
# - cd client && npm ci
# - cd client && npm run cy:verify
# - cd ..
# - npm ci
install:
- npm ci
# - chmod +x node_modules/.bin/*
# Do same for the client
- cd client && npm ci
- chmod +x node_modules/.bin/*
script:
# - cd ..
# - npm run build
# Build artifacts for client
- npm run build
- cd ..
before_deploy:
# Exclude the client folder from the deploy bundle
- sudo rm -rf client
- sudo rm -rfv docs
- sudo rm -fv README.MD
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: bZKytDSQ++lM2lGpil65/lt11+W6q1O5dwSWfnkSlSJt44rq0iTETruMTQcE/dY0SJwPKdbxWz5N/o9J4dXTURW6y5lNXPTbI66jGFmNH/JbAw8WWsOq9EfnEz0opbAePwSVaSNSiTxC44vHaTOCu4gYq+VXBes+PxivPFDHmtcwwZlwD6THq5NVcklrKUH5PBnYmNHRe2yFhk31Wej+lj3ISsEbL2Ing/mkXm/WFLrIAGVnaxdaQxztv627SkM/P2dkbUZuEvJjwISKj3WwGeH8o9XBvoFVZqJiNso3qfrpASd2n2D0J+/RXhDCwhlvuHppmtqM5Wj+aRe7dq3R1XulBniPA53A8GRakRJKrzv9Pllz17l0BB3eeIWm7wduy8w/O02CQvocFtMIgOJ/QfVukO1yXjTp5ckH5HsEhFKR/9wAWNXTDoHIZA3515/hrQyQAE3z49x8RSLLcauzdibPX/dyhKCfGQ56rUT6XRA6FSdgMbOPN/wCEkjx1bTq+3zF62HRVUocUcnCYUUoN4tq4SBbFvuGbecGRC4MxfeZFExqxRsbEXnrNxgD4sqYYhZFCnvoRvHQs5BY9Gbpmpf8KxzeuRuv3paAlDGjlGVoefJXy0PNKNpRaBfkX7oHkP6NLW4I2peDqLxSPG91eJbfV+NcQ2OWeah6TvPIlnk=
  app: mattrememberedproject
  on:
    repo: BantuLabTech/mattrememberedproject
    branch: master
  after_failure:
  - find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
env:
  global:
  - TEST_URL_ENV=http://localhost:8080
