language: node_js
node_js:
- lts/*
addons:
  apt:
    packages:
    - libgconf-2-4
services: 
cache:
  npm: true
  directories:
  - "~/.cache"
  - "./node_modules"
  - "~/.cache"
override:
- npm ci
- npm run cy:verify
install:
- npm ci
- chmod +x node_modules/.bin/*
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: LMYlO8sbqmnz9rFFuz6NjZhQrlCigledmEzO2Qv0M3Slyc3jxASehcZZTW3g8ThFk3LFDkT/dB+aZZmjTWo72xs+aoxazcH1zLoPuDrFwpONhU2yTFzYxAgEJjwRWbhjs/O1PSKT2e6k3t9G+3C/8ZWA6lGhjkEKL+9bHQzf4izR3D71o3vz36zgP1cVPnTdwkjb91dX/6yF6W65Ap9FWL9mSoVnmLP8e1yNOWbEE5r8SXd0h36i7WNWByuAG+lY8vtinDDwSZpZGM+jwOjNrBJ7sQoj3QyPonKA6Syd1t1BS3HWi9QPQ57OsU9aH8z7gIjkgyzJskygSxyt3w7cZJZJJGp8hK65RB6ceOflDuWUupjpqoyWAbP1OFQMNF7oR2hd1ITP3loBhajwCm3+kTqjzcOnJ/xoO/BJXQCaIFlrhrrtOqzBBm+DuRpXryAMunzS8mfJcpYh+ZQxjlnCmP09Qzg+vbNjbTFvsU633Lw9aA07KJsgm5GDl3stt/nFDmL4UVhy/CzHLgGa/Bx6ETrGygx5WZf9rFDDsWNv1pDQTZC6b3sN+DInjWQax3709nUPRnfc1jDQfDSP1ZSR1qKhLfTefQpd2DdHjxXqCZyU6ZCqZs43B/OYGOrh4GGTvQPPsJ4TuYRIb9nGpPGp32llBi4fuX28GJm9tdhUSX8=
  app: mattrememberedproject
  on:
    repo: BantuLabTech/mattrememberedproject
    branch: master
  after_failure:
  - find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
env:
  global:
  - TEST_URL_ENV=http://localhost:8080
  - secure: zYiRJ5ho2YEzmfa+4XhSLgijUVS3lsh7IAsarilARrmxuPf0MlpFq9THDP143B0AvO3RDF77nKybBgZ4ojdih9gVrNdzv+eQSTjiwafnQDb8tfXujRKYmlSfiY5v+DUyBFGNyW7RJUXUX5Wx2M49LlAANg8jc4nIrt+mUaQYyMA2aI+lBKOp/n6ww+b84SoP7Ycq7GcD/o8vk9iva0I9ZPEYhKZgY3dlBbCCLIbz7YYFpaAIsW7dR/VP89Mqfa+63g1jo8U6XTmDM0a8mQ0MPjR2MpnTC1I/J9CtxXl2jVBJWPEM9JFIvlrG59vW/vqcT0uVnJiB8IeKo2JrK26Zq7THGQsrfMlkUVMOZ+6Qj6hfRBh38VbwSSdRLEWQNsYf+uJKJ8G2oVyGKtvAacJIbZJRpdTKIjhH1k/5JeO81gspyMtfMR8cQIl6PHp7AeV2QVY8dGSGWvbiJpPVVlRLlzK70KFVJskZlRTsxids1kMNIQJP32jYGkoYwVuVHIZK+1I2k1pfrTsImYV6/ojCTu7Ur7O1R4s8XoFXHbdZ6C8qgyn8ZmL6TVh/FTa6XS30dfMvoLu7xQvwPYVMfMqhVf2vyYk53NUdrJ9Gx5UxOZv3fLxqX4L72PUoTJX562pSesbzUdr0hw9aBEJVLG8RgQ1UU5gfd9yx1vKRiFhc4P8=
